# Generated by Django 3.0.3 on 2020-02-10 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20200210_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280)),
                ('is_boast', models.BooleanField(default=True)),
                ('likes', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='ghostpost',
            name='title',
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='message',
            field=models.CharField(max_length=280),
        ),
    ]
