# Generated by Django 3.0.3 on 2020-02-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0003_auto_20200210_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='ghostpost',
            old_name='downvote',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='ghostpost',
            old_name='upvote',
            new_name='like',
        ),
    ]
