# Generated by Django 3.0.3 on 2020-02-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0004_auto_20200210_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='isRoast',
        ),
        migrations.RemoveField(
            model_name='ghostpost',
            name='total',
        ),
    ]
