# Generated by Django 3.0.3 on 2020-02-10 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0005_auto_20200210_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='submitDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
