# Generated by Django 3.0.3 on 2020-02-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0006_auto_20200210_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='submitDate',
        ),
    ]
