# Generated by Django 3.0.3 on 2020-02-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0008_ghostpost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
