# Generated by Django 3.0.3 on 2020-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0010_remove_ghostpost_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='is_Boast',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
